"""Normalize tables

Revision ID: d53d7b717b8a
Revises: 6d0eb3f3fee2
Create Date: 2026-09-14 23:32:55.769186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53d7b717b8a'
down_revision: Union[str, Sequence[str], None] = '6d0eb3f3fee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM lessons")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.add_column('lessons', sa.Column('teacher_id', sa.UUID(), nullable=False))
    op.add_column('lessons', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.add_column('lessons', sa.Column('room_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_lessons_subject_id', 'lessons', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key('fk_lessons_room_id', 'lessons', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key('fk_lessons_teacher_id', 'lessons', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('lessons', 'subject')
    op.drop_column('lessons', 'teacher')
    op.drop_column('lessons', 'room')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM lessons")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('room', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('teacher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_lessons_teacher_id', 'lessons', type_='foreignkey')
    op.drop_constraint('fk_lessons_room_id', 'lessons', type_='foreignkey')
    op.drop_constraint('fk_lessons_subject_id', 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'room_id')
    op.drop_column('lessons', 'subject_id')
    op.drop_column('lessons', 'teacher_id')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
